# Generated by Django 5.2.9 on 2025-12-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
                ('is_billable', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='messis.project')),
            ],
        ),
    ]
