# Generated by Django 5.2.9 on 2025-12-16 06:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0002_alter_company_name_alter_company_subdomain_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cost_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
