# Generated by Django 5.2.9 on 2025-12-16 06:37

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.management import create_permissions

from django.apps import apps

from messis.models import UserRole


def create_group_and_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    model_list = [
        'company',
        'customuser',
        'project',
        'project_team',
        'task',
        'userprofile',
        'userrole',
    ]

    content_type_list = ContentType.objects.filter(model__in=model_list).all()

    company_owner_group, company_owner_group_created = Group.objects.get_or_create(name=UserRole.Role.OWNER)

    for content_type in content_type_list:
        permissions = Permission.objects.filter(content_type__app_label=content_type.app_label,
                                                content_type__model=content_type.model)
        for permission in permissions:
            company_owner_group.permissions.add(permission)

class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0003_alter_company_managers_alter_userprofile_bill_rate_and_more'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permissions, lambda x, y: None)
    ]
