# Generated by Django 5.2.9 on 2025-12-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0004_group_and_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('USER', 'User')], default='USER', max_length=5),
        ),
    ]
