# Generated by Django 5.2.9 on 2025-12-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
    ]
