# Generated by Django 5.2.9 on 2025-12-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0006_alter_company_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
