# Generated by Django 5.2.9 on 2025-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0007_uploadimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(default='', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
