# Generated by Django 5.2.9 on 2025-12-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messis', '0008_customuser_invite_code_customuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('entry_at', models.DateField()),
                ('total_seconds', models.BigIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='time_entries', to='messis.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='time_entries', to='messis.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
